### PR TITLE
tools: Add script for documentation generation

### PR DESCRIPTION
**Pull request by javajawa**
Currently, the only generated documentation is the package map SVG.

### CODE REVIEW

**Comment by exachixkitsune** [comment]
Do we not, in some way, need to ask for "Graphviz" to be installed to make the graphs?
Source: https://pypi.org/project/pydeps/#how-to-install

Re-reading, noting now that's it's a separate program.

**Comment by javajawa** [comment]
> Do we not, in some way, need to ask for "Graphviz" to be installed to make the graphs? Source: https://pypi.org/project/pydeps/#how-to-install
> 
> Re-reading, noting now that's it's a separate program.

Notably it's a separate non-Python program (which is why it's not handles as a transitive dependency).
I'm personally happy for the failure mode to be whatever pydeps does is `dot` / `graphviz` is not present (though I do not know what that is)

**Comment by exachixkitsune** [comment]
> > Do we not, in some way, need to ask for "Graphviz" to be installed to make the graphs? Source: https://pypi.org/project/pydeps/#how-to-install
> > Re-reading, noting now that's it's a separate program.
> 
> Notably it's a separate non-Python program (which is why it's not handles as a transitive dependency). I'm personally happy for the failure mode to be whatever pydeps does is `dot` / `graphviz` is not present (though I do not know what that is)

It makes an empty .xml file, overwriting the previous.

**Review by exachixkitsune — APPROVED** [review]
Happy

**Pull request merged**
